# Copyright 2023 Ericsson AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: codechecker-bazel-unit-tests

# Triggers the workflow on push or pull request events.
on: [push, pull_request]

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  load_versions:
    name: "Load bazel versions for Unit tests"
    runs-on: ubuntu-24.04
    outputs:
      bazel_version: ${{ steps.generate_matrix.outputs.matrix_json }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Load versions
        id: generate_matrix
        run: |
          JSON=$(jq -c . ./.github/bazel_version.json)
          echo "matrix_json=$JSON" >> $GITHUB_OUTPUT

  ubuntu_test:
    name: "Unit tests: Bazel ${{ matrix.bazel_version }} (Ubuntu)"
    runs-on: ubuntu-24.04
    needs: load_versions
    strategy:
      fail-fast: false
      matrix:
        bazel_version: ${{ fromJson(needs.load_versions.outputs.bazel_version) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set bazel version to ${{ matrix.bazel_version }}
        run: echo "${{ matrix.bazel_version }}" > .bazelversion
        shell: bash

      - name: Setup environment
        uses: ./.github/platform_environment_setup/ubuntu

      - name: Print versions
        run: |
          bazel version
          CodeChecker version
          echo "[NOTE]: CodeChecker may find different analyzer binaries" \
               "when invoking directly, or in bazel's sandbox environment!" \
               "Be sure to double check during debugging."
          CodeChecker analyzers

      - name: Run tests
        run: |
          cd test
          python3 -m unittest discover unit -vvv

  rhel9_test:
    name: "Unit tests: Bazel ${{ matrix.bazel_version }} (RHEL9)"
    runs-on: ubuntu-24.04
    container:
      image: redhat/ubi9:latest
      options: --init
    needs: load_versions
    strategy:
      fail-fast: false
      matrix:
        bazel_version: ${{ fromJson(needs.load_versions.outputs.bazel_version) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set bazel version to ${{ matrix.bazel_version }}
        run: echo "${{ matrix.bazel_version }}" > .bazelversion
        shell: bash

      - name: Setup environment
        uses: ./.github/platform_environment_setup/rhel9

      - name: Print versions
        run: |
          bazel version
          CodeChecker version
          echo "[NOTE]: CodeChecker may find different analyzer binaries" \
               "when invoking directly, or in bazel's sandbox environment!" \
               "Be sure to double check during debugging."
          CodeChecker analyzers

      - name: Run tests
        run: |
          cd test
          runuser -u test -- python3 -m unittest discover unit -vvv
